services:
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:${GRAFANA_VERSION}
    ports:
      - 3000:3000
    volumes:
      - ../hydrolix-hydrolix-datasource:/var/lib/grafana/plugins/hydrolix-hydrolix-datasource
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/login"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - GF_LOG_LEVEL=debug
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true
      - NODE_ENV=development
      - GF_LOG_FILTERS=plugin.hydrolix-hydrolix-datasource:debug
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=1
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=hydrolix-hydrolix-datasource
    networks:
      - grafana

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "clickhouse-server", "--query", "SELECT 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ../testdata/containers:/testdata
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=1
      - CLICKHOUSE_SKIP_USER_SETUP=0
      - CLICKHOUSE_USER=testuser
      - CLICKHOUSE_PASSWORD=testpass
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

    entrypoint:
      - /bin/bash
      - -c
      - |
        cp /testdata/tcconfig.xml /etc/clickhouse-server/config.d/tcconfig.xml
        cp /testdata/initdb.sql /docker-entrypoint-initdb.d/initdb.sql
        exec /entrypoint.sh "$@"
    networks:
      - grafana

networks:
  grafana: