stages:
  - prepare
  - build
  - package
  - test
  - security
  - cleanup

include:
  - local: .gitlab/ci/.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

sast:
  variables:
    SAST_EXCLUDED_PATHS: "e2e"
    SEARCH_MAX_DEPTH: '5'
  stage: security

.sast-analyzer:
  tags: [forecast-small]

semgrep-sast:
  rules:
    - if: $SECURITY
    - if: $BLESSING
      when: never
    - if: $SANITY
      when: never
    - if: $RELEASE_DEBUG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

sobelow-sast:
  rules:
    - if: $SECURITY
    - if: $BLESSING
      when: never
    - if: $SANITY
      when: never
    - if: $RELEASE_DEBUG
      when: never

.secret-analyzer:
  tags: [forecast-small]

secret_detection:
  stage: security
  rules:
    - if: $SECURITY
    - if: $BLESSING
      when: never
    - if: $SANITY
      when: never
    - if: $RELEASE_DEBUG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

.ds-analyzer:
  variables:
    DS_MAX_DEPTH: -1
  tags: [forecast-small]

gemnasium-dependency_scanning:
  stage: security
  rules:
    - if: $SECURITY
    - if: $BLESSING
      when: never
    - if: $SANITY
      when: never
    - if: $RELEASE_DEBUG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

gemnasium-maven-dependency_scanning:
  stage: security
  rules:
    - when: never

gemnasium-python-dependency_scanning:
  stage: security
  rules:
    - if: $SECURITY
    - if: $BLESSING
      when: never
    - if: $SANITY
      when: never
    - if: $RELEASE_DEBUG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"