version: "3.4"
x-common-variables: &common-variables
  CLUSTER_NODE: demo.trafficpeak.live
  REDIS_USERNAME: chproxy
  REDIS_PASSWORD:
  HYDROLIX_USERNAME:
  HYDROLIX_PASSWORD:
  GF_INSTALL_PLUGINS: "grafana-clickhouse-datasource 4.8.2"
volumes:
  prometheus_data: {}
services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    container_name: grafana-dashboards
    environment: *common-variables
    build:
      args:
        development: false
