name: Publish Plugin

on:
  workflow_dispatch:
    inputs:
      publish_to_aws:
        description: 'Publish to AWS S3'
        required: true
        default: true
        type: boolean

jobs:
  publish-aws:
    name: Publish to AWS S3
    runs-on: ubuntu-latest
    if: inputs.publish_to_aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          commit: ${{github.event.pull_request.head.sha}}
          name: plugin-package
          
      - name: Publish to S3
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./.github/scripts/publish-aws.sh