.if-default-branch: &if-default-branch
  if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_IID == null"

.if-release-branch: &if-release-branch
  if: '$CI_COMMIT_BRANCH =~ /^release[\/\-_].+$/'

.if-merge-request: &if-merge-request
  if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train"'

.if-release-merge-request: &if-release-merge-request
  if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release[\/\-_].+$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

.if-schedule-pipeline: &if-schedule-pipeline
  if: '$CI_PIPELINE_SOURCE == "schedule"'

.if-force-pipeline: &if-force-pipeline
  if: "$FORCE_PIPELINE"

.npm-cache-patterns: &npm-cache-patterns
  - ".cache/npm/"
  - "node_modules/"
  - "package-lock.json"

.go-cache-patterns: &go-cache-patterns
  - ".cache/go-mod/"

.rules:build:
  rules:
    - <<: *if-merge-request
    - <<: *if-force-pipeline

.rules:release:
  rules:
    - <<: *if-release-merge-request

.npm-cache-push:
  cache:
    - key: npm-$CI_COMMIT_REF_SLUG
      paths: *npm-cache-patterns
      policy: push

.npm-cache-pull:
  cache:
    - key: npm-$CI_COMMIT_REF_SLUG
      paths: *npm-cache-patterns
      policy: pull

.go-cache-pull-push:
  cache:
    - key: go-$CI_COMMIT_REF_SLUG
      paths: *go-cache-patterns
      policy: pull-push

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.cache/npm"
  GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/go-mod"
  DOCKER_TLS_CERTDIR: "/certs"
  KUBERNETES_CPU_LIMIT: "12"
  KUBERNETES_CPU_REQUEST: "12"
  KUBERNETES_MEMORY_REQUEST: "16Gi"
  KUBERNETES_MEMORY_LIMIT: "16Gi"
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "16Gi"
  KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "16Gi"

prepare-frontend:
  extends:
    - .npm-cache-push
    - .rules:build
  stage: prepare
  image: node:22
  tags: [gitlab-org]
  script:
    - npm install

build-frontend:
  extends:
    - .npm-cache-pull
    - .rules:build
  stage: build
  image: node:22
  tags: [gitlab-org]
  script:
    - npx tsc
    - npm run build
  artifacts:
    paths:
      - dist/
    when: on_success
    expire_in: 1 hour

test-frontend:
  extends:
    - .npm-cache-pull
    - .rules:build
  stage: test
  image: node:22
  tags: [gitlab-org]
  variables:
    ESLINT_CODE_QUALITY_REPORT: eslint_report.json
    JEST_JUNIT_OUTPUT_FILE: junit_report.xml
  script:
    - npx tsc
    - npm run lint
    - npm run test:ci
  coverage: /^Statements\s*:\s*([^%]+)/
  artifacts:
    reports:
      codequality: eslint_report.json
      junit: junit_report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

build-backend:
  extends:
    - .go-cache-pull-push
    - .rules:build
  stage: build
  image: golang:1.23
  tags: [lke]
  before_script:
    - go install github.com/magefile/mage@latest
  script:
    - mage
  artifacts:
    paths:
      - dist/
    when: on_success
    expire_in: 1 hour

test-backend:
  extends:
    - .go-cache-pull-push
    - .rules:build
  stage: test
  image: golang:1.23
  services:
    - name: clickhouse/clickhouse-server:latest
      alias: ch
      variables:
        CLICKHOUSE_SKIP_USER_SETUP: 1
      entrypoint:
        - /bin/bash
        - -c
        - |
          sed -i 's|<custom_settings_prefixes>SQL_</custom_settings_prefixes>|<custom_settings_prefixes>hdx_</custom_settings_prefixes>|' $CLICKHOUSE_CONFIG
          exec /entrypoint.sh "$@"
  tags: [gitlab-org]
  variables:
    CLICKHOUSE_HOSTNAME: ch
  before_script:
    - go install gotest.tools/gotestsum@latest
    - go install github.com/boumenot/gocover-cobertura@latest
  script:
    - gotestsum --junitfile junit_report.xml --format testname -- -race -coverprofile=coverage.txt -covermode atomic $(go list ./... | grep -v /testhelpers)
    - gocover-cobertura < coverage.txt > cobertura-coverage.xml
    - go tool cover -func coverage.txt
  coverage: /total:\s+\(statements\)\s+\d+.\d+%/
  artifacts:
    reports:
      junit: junit_report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura-coverage.xml

zip:
  extends:
    - .npm-cache-pull
    - .rules:build
  stage: package
  image: node:22
  needs: [build-frontend, build-backend]
  tags: [gitlab-org]
  before_script:
    - apt -qy update && apt -qy install zip
  script:
    - PLUGIN_NAME=$(npm pkg get name | tr -d '"')
    - PLUGIN_VERSION=$(npm pkg get version | tr -d '"')
    - ZIP_NAME=$PLUGIN_NAME-$PLUGIN_VERSION.zip
    - mv dist/ $PLUGIN_NAME/
    - zip $ZIP_NAME $PLUGIN_NAME -r
  artifacts:
    paths:
      - "*.zip"
    when: on_success
    expire_in: 7 days

.e2e-base:
  stage: e2e
  parallel:
    matrix:
      - E2E_GRAFANA_NAME: ["grafana-enterprise"]
        E2E_GRAFANA_VERSION: ["10.4.16", "11.5.2"]
  variables:
    E2E_IMAGE_NAME: e2e-$E2E_GRAFANA_NAME-$E2E_GRAFANA_VERSION
    E2E_IMAGE_TAG: $CI_COMMIT_SHA
    E2E_IMAGE: $CI_REGISTRY/hydrolix/grafana-datasource-plugin/$E2E_IMAGE_NAME:$E2E_IMAGE_TAG
    E2E_GRAFANA_URL: http://e2e:3000
    PLAYWRIGHT_JUNIT_OUTPUT_FILE: junit_report.xml

build-e2e-image:
  extends:
    - .e2e-base
    - .npm-cache-pull
    - .rules:build
  image: docker:28
  services:
    - docker:28-dind
  needs: [zip]
  tags: [gitlab-org-docker]
  script:
    - unzip "$(ls -1 *.zip | head -n 1)" -d .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f .gitlab/e2e.Dockerfile -t $E2E_IMAGE --build-arg E2E_GRAFANA_NAME=$E2E_GRAFANA_NAME --build-arg E2E_GRAFANA_VERSION=$E2E_GRAFANA_VERSION .
    - docker push $E2E_IMAGE

e2e:
  extends:
    - .e2e-base
    - .npm-cache-pull
    - .rules:build
  image: mcr.microsoft.com/playwright:v1.50.0-jammy
  services:
    - name: $E2E_IMAGE
      alias: e2e
  needs: [build-e2e-image, test-frontend, test-backend]
  tags: [gitlab-org]
  before_script:
    - npx playwright install
  script:
    - npx playwright test --reporter=junit
  artifacts:
    reports:
      junit: junit_report.xml

remove-e2e-image:
  extends:
    - .e2e-base
    - .npm-cache-pull
    - .rules:build
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
  when: always
  needs: [e2e]
  tags: [gitlab-org]
  script:
    - .gitlab/remove-image.sh "$CI_JOB_TOKEN" "$CI_PROJECT_ID" "$E2E_IMAGE_NAME" "$E2E_IMAGE_TAG"

publish:
  extends:
    - .rules:release
  stage: publish
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
  when: manual
  needs: [zip, e2e]
  tags: [gitlab-org]
  script:
    - .gitlab/publish.sh
